require: rubocop-rspec
AllCops:
  RunRailsCops: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
Documentation:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 100
MultilineOperationIndentation:
  EnforcedStyle: 'indented'
Rails:
  Enabled: true
RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'
    - 'spec/routing/*'
RSpec/MultipleExpectations:
  Max: 2
StringLiterals:
  Enabled: false
Style/VariableNumber:
  EnforcedStyle: 'snake_case'
